import {
  Feather, Heart, Globe, House, Plus, Users, Check, FileText, Store,
  DollarSign, BarChart3, User, Shield, LogIn, Mail, Lock, Phone,
  AlertTriangle, Calendar, Clock, MapPin, Church, Hand,
  Package, ClipboardList, Star, Pencil, Search, Menu, Trash2,
  Save, Eye, Info, X, ChevronUp, ChevronDown, CreditCard,
  Hourglass, Music, BookOpen, MessageCircle, Sparkles, Mic,
  Flame, Volume2, Film, Image, Share2, Printer, Link,
  ArrowLeft, ArrowRight, ExternalLink, Sun, Moon, HelpCircle,
  MoreVertical, Settings, Bell, ShieldAlert, Hash, Upload,
  PartyPopper, UserPlus, UserCheck,
} from 'lucide-react'

const iconMap = {
  dove: Feather,
  heart: Heart,
  'green-heart': Heart,
  globe: Globe,
  home: House,
  house: House,
  plus: Plus,
  add: Plus,
  users: Users,
  people: Users,
  check: Check,
  done: Check,
  complete: Check,
  'file-text': FileText,
  file: FileText,
  document: FileText,
  store: Store,
  shop: Store,
  vendor: Store,
  money: DollarSign,
  cash: DollarSign,
  'dollar-sign': DollarSign,
  chart: BarChart3,
  'bar-chart': BarChart3,
  stats: BarChart3,
  user: User,
  person: User,
  profile: User,
  shield: Shield,
  admin: Shield,
  login: LogIn,
  mail: Mail,
  email: Mail,
  lock: Lock,
  password: Lock,
  phone: Phone,
  mobile: Phone,
  warning: AlertTriangle,
  alert: AlertTriangle,
  danger: AlertTriangle,
  calendar: Calendar,
  date: Calendar,
  clock: Clock,
  time: Clock,
  'map-pin': MapPin,
  location: MapPin,
  venue: MapPin,
  church: Church,
  officiant: Church,
  hand: Hand,
  wave: Hand,
  package: Package,
  box: Package,
  'clipboard-list': ClipboardList,
  clipboard: ClipboardList,
  tasks: ClipboardList,
  star: Star,
  rating: Star,
  pencil: Pencil,
  edit: Pencil,
  search: Search,
  magnify: Search,
  menu: Menu,
  hamburger: Menu,
  'trash-2': Trash2,
  trash: Trash2,
  delete: Trash2,
  remove: Trash2,
  save: Save,
  floppy: Save,
  eye: Eye,
  view: Eye,
  preview: Eye,
  info: Info,
  'chevron-up': ChevronUp,
  up: ChevronUp,
  'chevron-down': ChevronDown,
  down: ChevronDown,
  'credit-card': CreditCard,
  card: CreditCard,
  hourglass: Hourglass,
  pending: Hourglass,
  music: Music,
  hymn: Music,
  'book-open': BookOpen,
  book: BookOpen,
  reading: BookOpen,
  'message-circle': MessageCircle,
  chat: MessageCircle,
  message: MessageCircle,
  condolences: MessageCircle,
  sparkles: Sparkles,
  tribute: Sparkles,
  mic: Mic,
  microphone: Mic,
  speech: Mic,
  candle: Flame,
  ritual: Flame,
  'volume-2': Volume2,
  announcement: Volume2,
  film: Film,
  video: Film,
  livestream: Film,
  image: Image,
  photo: Image,
  gallery: Image,
  'share-2': Share2,
  share: Share2,
  printer: Printer,
  print: Printer,
  link: Link,
  url: Link,
  'arrow-left': ArrowLeft,
  back: ArrowLeft,
  'arrow-right': ArrowRight,
  next: ArrowRight,
  'external-link': ExternalLink,
  sun: Sun,
  moon: Moon,
  'help-circle': HelpCircle,
  help: HelpCircle,
  'more-vertical': MoreVertical,
  more: MoreVertical,
  settings: Settings,
  gear: Settings,
  bell: Bell,
  notification: Bell,
  'shield-alert': ShieldAlert,
  'no-entry': ShieldAlert,
  hash: Hash,
  hashtag: Hash,
  upload: Upload,
  photoUpload: Upload,
  'party-popper': PartyPopper,
  celebrate: PartyPopper,
  'user-plus': UserPlus,
  register: UserPlus,
  'user-check': UserCheck,
  verified: UserCheck,
}

export default function Icon({ name, size = 18, className = '', style = {}, ...props }) {
  const LucideIcon = iconMap[name?.toLowerCase()]
  if (!LucideIcon) return <span className={className} style={style}>{name}</span>
  return <LucideIcon size={size} className={className} style={{ verticalAlign: 'middle', ...style }} {...props} />
}

export { iconMap }
